# -*- coding: utf-8 -*-
"""face detection,py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10X645mreYJbKcDDD6UZVniVRCbD_QoL-
"""

!pip install opencv-python face-recognition

from google.colab import files
files.upload()

import cv2
import face_recognition
import matplotlib.pyplot as plt

# Load known image (reference)
known_image = face_recognition.load_image_file("known.jpg")
known_encoding = face_recognition.face_encodings(known_image)[0]

# Load test image
test_image = face_recognition.load_image_file("test.jpg")
face_locations = face_recognition.face_locations(test_image)
face_encodings = face_recognition.face_encodings(test_image, face_locations)

# Convert image for OpenCV
test_image_cv = cv2.cvtColor(test_image, cv2.COLOR_RGB2BGR)

for (top, right, bottom, left), face_encoding in zip(face_locations, face_encodings):
    matches = face_recognition.compare_faces([known_encoding], face_encoding)

    name = "Unknown"
    if matches[0]:
        name = "Recognized Face"

    # Draw rectangle & label
    cv2.rectangle(test_image_cv, (left, top), (right, bottom), (0, 255, 0), 2)
    cv2.putText(test_image_cv, name, (left, top - 10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

# Display output
plt.imshow(cv2.cvtColor(test_image_cv, cv2.COLOR_BGR2RGB))
plt.axis("off")